# Generated by Django 3.1.2 on 2020-11-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=16, unique=True)),
                ('s_password', models.CharField(max_length=128)),
                ('s_token', models.CharField(max_length=256)),
            ],
        ),
    ]
